### PR TITLE
Update to PyCharm 2016.2

### PR DESCRIPTION
**Pull request by allanlewis**
This PR updates the base release to the latest upstream, 2016.2. I've built the RPM on Fedora 23; I'm currently checking there aren't any regressions with regard to plugins, given the recent issues.

### CODE REVIEW

**Comment by allanlewis** [comment]
I noticed some plugins have been updated, so I might as well include those in this PR: coming up...

**Comment by allanlewis** [comment]
I've updated the plugins, now testing again...

**Comment by phracek** [comment]
Thanks for updating. How can I test it before merging? Any idea

**Comment by allanlewis** [comment]
It's working fine for me. I think it would be good to set up builds on Travis; my commit allanlewis/pycharm-community-edition@89782ed might be a good place to start.

**Comment by allanlewis** [comment]
Thanks @phracek.

**Comment by allanlewis** [comment]
I don't understand what you're doing with Travis: it's using the default config, which calls `rake` (Ruby) - perhaps use my config as a starting point?

**Pull request merged**
