### PR TITLE
Add png to icons/hicolor/scalable/apps/pycharm-community.png

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by xvitaly** [comment]
`scalable` directory can be used only with SVG icons (Scalable Vector Graphics). PNG icons without fixed size must be placed in `pixmaps`.

Also SVG icons are supported by all DEs and will automatically scale based on the preferred side of the icon.

**Comment by xvitaly** [comment]
Also please configure COPR auto-build to use only `master` branch.

COPR already built this PR multiple times: https://copr.fedorainfracloud.org/coprs/phracek/PyCharm/builds/

**Comment by phracek** [comment]
See issue: https://pagure.io/copr/copr/issue/2039

**Comment by xvitaly** [comment]
> See issue

Placing PNG icon into SVG directory is not good at all.

We need to generate PNG icons for different sizes from this SVG and place them in the appropriate directories, just like I did in SpeedCrunch: https://src.fedoraproject.org/rpms/speedcrunch/blob/rawhide/f/speedcrunch.spec#_48

**Comment by xvitaly** [comment]
I can push a better fix to the `fix_icon` branch.

**Comment by xvitaly** [comment]
Committed.

**Review by xvitaly — APPROVED** [review]
LGTM now. Let's check if it builds and I will merge it and then rebuild packages.

**Pull request merged**
